all:
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C async_ipc
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C sync_ipc

clean:
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C async_ipc clean
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C sync_ipc clean