SDK_FILES = \
	$(srcdir)/Penglai-sdk-TVM/enclave-driver/penglai.ko \
	$(srcdir)/Penglai-sdk-TVM/demo/host/host \
	$(srcdir)/Penglai-sdk-TVM/demo/fork-host/fork-host \
	$(srcdir)/Penglai-sdk-TVM/demo/hello-world/hello-world \
	$(srcdir)/Penglai-sdk-TVM/demo/relay-page/relay-page \
	$(srcdir)/Penglai-sdk-TVM/demo/mem/mem \
	$(srcdir)/Penglai-sdk-TVM/demo/IPC/caller/caller \
	$(srcdir)/Penglai-sdk-TVM/demo/IPC/server/server \
	$(srcdir)/Penglai-sdk-TVM/demo/IPC/server1/server1 \
	$(srcdir)/Penglai-sdk-TVM/demo/IPC/test-caller/test-caller \
	$(srcdir)/Penglai-sdk-TVM/demo/FS/fshost/fshost \
	$(srcdir)/Penglai-sdk-TVM/demo/FS/testfs/testfs \
	$(srcdir)/Penglai-sdk-TVM/demo/FS/littlefs/lfs \
	$(srcdir)/Penglai-sdk-TVM/demo/test-stop/host/test-stop \
	$(srcdir)/Penglai-sdk-TVM/demo/test-stop/loop/loop \
	$(srcdir)/Penglai-sdk-TVM/demo/psa/psa_host/psahost \
	$(srcdir)/Penglai-sdk-TVM/demo/psa/psa_server/psa_server \
	$(srcdir)/Penglai-sdk-TVM/demo/psa/psa_client/psa_client \
	$(srcdir)/Penglai-sdk-TVM/demo/psa/psa_key_ladder/psa_key_ladder \
	$(srcdir)/Penglai-sdk-TVM/demo/psa/psa_crypto/psa_crypto \
	$(srcdir)/Penglai-sdk-TVM/demo/seperated_filesystem_simple/decouplefs_simple \
	$(srcdir)/Penglai-sdk-TVM/demo/IPC-Manager/ipc_manager \
	$(srcdir)/Penglai-sdk-TVM/demo/IPC-Micro/async_ipc/async_ipc \
	$(srcdir)/Penglai-sdk-TVM/demo/IPC-Micro/sync_ipc/sync_ipc \
	$(srcdir)/Penglai-sdk-TVM/demo/image-process/async/async_img_process \
	$(srcdir)/Penglai-sdk-TVM/demo/image-process/sync/sync_img_process \
	$(srcdir)/Penglai-sdk-TVM/demo/sqlite/sqlite_async/sqlite_async \
	$(srcdir)/Penglai-sdk-TVM/demo/sqlite/sqlite_sync/sqlite_sync \
	$(srcdir)/Penglai-sdk-TVM/demo/sqlite/sqlite_baseline/sqlite_baseline