all:
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C sync
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C async
clean:
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C sync clean
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C async clean