all:
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  host
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  loop

clean:
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  host clean
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  loop clean
