h51812
s 00000/00002/00131
d D 1.4 93/05/16 14:45:37 lm 5 4
c none
cC
cK06578
cSAlpha2.11
e
s 00011/00001/00122
d D 1.3 93/04/13 06:00:23 lm 4 3
c add randoms
cK07034
e
s 00004/00002/00119
d D 1.2 92/06/02 02:24:55 lm 3 2
c none
cK38246
cZ-07:00
e
s 00121/00000/00000
d D 1.1 92/02/27 02:35:17 lm 2 1
c date and time created 92/02/27 10:35:17 by lm
cK38635
e
s 00000/00000/00000
d D 1.0 92/02/27 02:35:16 lm 1 0
cBlm@lm.bitmover.com|ChangeSet|20000131225335|47351|--LMBENCH--
cHlm.bitmover.com
cK33921
cPsrc/lmdd.1
cRdf9fa92cb54a1f00
cV4
cX0x21
cZ-08:00
e
u
U
f e 0
f x 0x21
t
T
I 2
.\" %W% %G%
.TH LMDD 1 
.SH NAME
lmdd \- move io for performance and debugging tests
.SH SYNOPSIS
.B lmdd
[
.IB option = value
] .\|.\|.
.SH DESCRIPTION
.B lmdd
copies a specified input file to a specified output with possible
conversions.  This program is primarily useful for timing I/O since it
prints out the timing statistics after completing.
.SH OPTIONS
.TP 15
.BI if= name
Input file is taken from
.IR name ;
D 3
standard input is default.
E 3
.I internal
I 3
is the default.
.I internal
E 3
is a special file that acts like Sun's 
.IR /dev/zero ,
i.e., it provides a buffer of zeros without doing a system call to get them.
.TP 
.BI of= name
Output file is taken from
.IR name ;
D 3
standard output is default.  
E 3
.I internal
I 3
is the default.
.I internal
E 3
is a special file that acts like 
.IR /dev/null ,
without doing a system call to get rid of the data.
.TP 
.BI bs= n
Input and output block size
.I n
bytes (default 8192).  Note that this is different from dd(1), it has
a 512 byte default.   Also note that the block size can be followed
by 'k' or 'm' to indicate kilo bytes (*1024) or megabytes (*1024*1024),
respectively.
.TP 
.BI ipat= n
If 
.B n
is non zero, expect a known pattern in the file (see opat).  Mismatches
will be displayed as "ERROR: off=%d want=%x got=%x".  The pattern is
a sequence of 4 byte integers with the first 0, second 1, and so on.
The default is not to check for the pattern.
.TP
.BI opat= n
If 
.B n
is non zero, generate a known pattern on the output stream.  Used for
debugging file system correctness.
The default is not to generate the pattern.
.TP 
.BI mismatch= n
If 
.B n
is non zero, stop at the first mismatched value.  Used with ipat.
.TP 
.BI skip= n
Skip
.IR n ""
input blocks before starting copy.
.TP 
.BI fsync= n
If
.I n
is non-zero, call fsync(2) on the output file before exiting or printing
timing statistics.
.TP 
.BI sync= n
If
.I n
is non-zero, call sync(2) before exiting or printing
timing statistics.
.TP 
I 4
.BI rand= n
D 5
If
.I n
E 5
This argument, by default off, turns on random behavior.  The argument is
not a flag, it is a size, that size is used as the upper bound for the 
seeks.
Also note that the block size can be followed
by 'k' or 'm' to indicate kilo bytes (*1024) or megabytes (*1024*1024),
.TP 
E 4
.BI flush= n
If
.I n
is non-zero and mmap(2) is available, call msync(2) to invalidate the
output file.  This flushes the file to disk so that you don't have
unmount/mount.  It is not as good as mount/unmount because it just
flushes file pages - it misses the indirect blocks which are still
D 4
cached.
E 4
I 4
cached.  Not supported on all systems, compile time option.
E 4
.TP 
.BI rusage= n
If
.I n
is non-zero, print rusage statistics as well as timing statistics.
I 4
Not supported on all systems, compile time option.
E 4
.TP 
.BI count= n
Copy only
.IR n ""
input records.
.SH EXAMPLES
.LP
This is the most common usage, the intent is to measure disk performance.
The disk is a spare partition mounted on /spare.
.sp
.nf
.in +4
# mount /spare
# lmdd if=internal of=/spare/XXX count=1000 fsync=1
7.81 MB in 3.78 seconds (2.0676 MB/sec)

: Flush cache
# umount /spare
# mount /spare

# lmdd if=/spare/XXX of=internal 
7.81 MB in 2.83 seconds (2.7611 MB/sec)
.in
.sp
.fi
.SH AUTHOR
Larry McVoy, lm@sun.com
.br
Not copyrighted.
E 2
I 1
E 1
