h27817
s 00020/00004/00032
d D 1.2 00/10/16 17:13:50 staelin 3 2
c - Update man pages to match current status
cC
cHhpli8.hpli.hpl.hp.com
cK44475
cZ+02:00
e
s 00036/00000/00000
d D 1.1 94/11/18 01:26:35 lm 2 1
c Initial revision
cC
cK23367
e
s 00000/00000/00000
d D 1.0 94/11/18 01:26:34 lm 1 0
cBlm@lm.bitmover.com|ChangeSet|20000131225335|47351|--LMBENCH--
cHlm.bitmover.com
cK03779
cPdoc/lat_udp.8
cR44c63df220a6d3a2
cV4
cX0x23
cZ-08:00
e
u
U
f e 0
f x 0x23
t
lmbench doc checkin
T
I 2
.\" $Id$
.TH LAT_UDP 8 "$Date$" "(c)1994 Larry McVoy" "LMBENCH"
.SH NAME
lat_udp \- measure interprocess communication latency via UDP/IP
.SH SYNOPSIS
.B lat_udp
.I -s
.sp .5
.B lat_udp
I 3
[
.I "-m <message size>"
]
[
.I "-P <parallelism>"
]
[
.I "-W <warmups>"
]
[
.I "-N <repetitions>"
]
E 3
.I hostname
.sp .5
.B lat_udp
D 3
.I -hostname
E 3
I 3
.I "-S hostname"
E 3
.SH DESCRIPTION
.B lat_udp
is a client/server program that measures interprocess
D 3
communication latencies.  The benchmark passes a token back and forth between
E 3
I 3
communication latencies.  The benchmark passes a message back and forth between
E 3
the two processes (this sort of benchmark is frequently referred to as a
``hot potato'' benchmark).  No other work is done in the processes.
.LP
.B lat_udp
has three forms of usage: as a server (-s), as a client (lat_udp localhost), and
D 3
as a shutdown (lat_udp -localhost).
E 3
I 3
as a shutdown (lat_udp -S localhost).
E 3
.SH OUTPUT
The reported time is in microseconds per round trip and includes the total
time, i.e., the context switching overhead is included.
Output format is like so
.sp
.ft CB
UDP latency using localhost: 650 microseconds
.ft
.SH ACKNOWLEDGEMENT
Funding for the development of
this tool was provided by Sun Microsystems Computer Corporation.
.SH "SEE ALSO"
D 3
lmbench(8).
E 3
I 3
lmbench(8), lat_fcntl(8), lat_fifo(8), lat_tcp(8), lat_unix(8).
.SH "AUTHOR"
Carl Staelin and Larry McVoy
.PP
Comments, suggestions, and bug reports are always welcome.
E 3
E 2
I 1
E 1
