#
# rv8-benchmark
#

all:
	make -C host
	make -C aes
	make -C dhrystone
	make -C norx
	make -C primes
	make -C qsort
	make -C sha512

clean:
	make -C host clean
	make -C aes clean
	make -C dhrystone clean
	make -C norx clean
	make -C primes clean
	make -C qsort clean
	make -C sha512 clean
