#!/bin/sh

#if [ X$CC = X ]
#then	CC=cc
#	for p in `echo $PATH | sed 's/:/ /g'`
#	do	if [ -f $p/gcc ]
#		then	CC=gcc
#		fi
#	done
#fi

if [ 1 ]
then
  CC=$MULTILIB_TOOLCHAIN/riscv64-unknown-linux-gnu-gcc
fi

echo $CC
