enum psa_status_e
{
    PSA_CALL_SUCCESS = 0,
    PSA_CALL_PARTITION_BUSY,
    PSA_CALL_ERROR_SECURE_DOMAIN_LOCKED,
    PSA_CALL_ERROR_INVALID_PARAMETER,
    PSA_CALL_ERROR_PARTITION_NON_REENTRANT,
    PSA_CALL_ERROR_NS_THREAD_MODE_CALL,
    PSA_CALL_ERROR_NOT_INITIALIZED,
    PSA_CALL_ERROR_NO_ACTIVE_PARTITION,
    PSA_CALL_ERROR_INVALID_EXC_MODE,
    PSA_CALL_SECURE_LOCK_FAILED,
    PSA_CALL_SECURE_UNLOCK_FAILED,
    PSA_CALL_ERROR_GENERIC = 0x1F,
};