APP = psa_server
APP_C_SRCS = psa_server.c psa_protected_storage.c psa_object_server.c psa_object_table.c psa_encrypted_object.c psa_crypto_interface.c
EXTRA_CLEAN = $(APP).dump
include $(PENGLAI_SDK)/app.mk
